"use client";

import { useState } from "react";
import { Chatbot } from "@/components/chatbot/Chatbot";
import type { PracticeContext } from "@/lib/practice-context";
import type { Job } from "@/lib/jobs";

type Props = {
  jobId: string;
  ctx: PracticeContext;
  v0?: Job["v0"];
};

export function PilotTemplate({ jobId, ctx, v0 }: Props) {
  // v0 builds stream into the demoUrl as they progress. Status starts as
  // "pending" and transitions to "completed" — show the iframe in both cases
  // so users see the build live. Fall back only when there's no demoUrl.
  if (v0?.demoUrl) {
    return <V0PilotShell jobId={jobId} ctx={ctx} demoUrl={v0.demoUrl} />;
  }
  return <FixedFallback jobId={jobId} ctx={ctx} />;
}

function V0PilotShell({
  jobId,
  ctx,
  demoUrl,
}: {
  jobId: string;
  ctx: PracticeContext;
  demoUrl: string;
}) {
  return (
    <div className="relative min-h-screen w-full bg-white" data-pilot-id={jobId}>
      <Watermark name={ctx.name} />
      <iframe
        src={demoUrl}
        className="block h-screen w-full border-0"
        title={`${ctx.name} — pilot site generated by v0`}
        sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
      />
      <FloatingChat ctx={ctx} />
    </div>
  );
}

function FloatingChat({ ctx }: { ctx: PracticeContext }) {
  const [open, setOpen] = useState(false);
  const primary = ctx.brand.primary;
  return (
    <div className="fixed bottom-4 right-4 z-40 flex flex-col items-end gap-3">
      {open && (
        <div className="w-[min(420px,calc(100vw-2rem))] overflow-hidden rounded-2xl shadow-2xl ring-1 ring-black/5">
          <Chatbot
            practiceContext={ctx}
            greeting={`Hi! I'm the ${ctx.name} assistant. Ask me anything about treatments, prices, the team, or book an appointment.`}
          />
        </div>
      )}
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="inline-flex items-center gap-2 rounded-full px-4 py-3 text-sm font-semibold text-white shadow-lg transition hover:scale-105"
        style={{ background: primary }}
      >
        {open ? "Close chat" : `Chat with ${ctx.name}`}
      </button>
    </div>
  );
}

function Watermark({ name }: { name: string }) {
  return (
    <div className="fixed top-3 right-3 z-50">
      <a
        href="/"
        className="inline-flex items-center gap-1.5 rounded-full bg-black/70 px-3 py-1 text-[11px] font-medium text-white backdrop-blur"
      >
        <span className="flex h-3 w-3 items-center justify-center rounded bg-white/90 text-[9px] font-bold text-black">
          M
        </span>
        Mirror pilot · {name}
      </a>
    </div>
  );
}

// Fallback used when v0 compose failed or hasn't run yet.
// Mirrors the original fixed template, kept terse.
function FixedFallback({ jobId, ctx }: { jobId: string; ctx: PracticeContext }) {
  const themeStyle = {
    "--brand-primary": ctx.brand.primary,
    "--brand-secondary": ctx.brand.secondary,
    "--brand-accent": ctx.brand.accent,
    fontFamily: ctx.brand.fontFamily ?? "Inter, system-ui, sans-serif",
    color: "#1a1a1a",
  } as React.CSSProperties;
  const featuredTreatments = ctx.treatments.slice(0, 6);

  return (
    <div style={themeStyle} className="min-h-screen" data-pilot-id={jobId}>
      <Watermark name={ctx.name} />
      <header
        className="px-6 py-5"
        style={{ background: ctx.brand.primary, color: "white" }}
      >
        <div className="mx-auto flex max-w-5xl items-center justify-between">
          <div>
            <div className="text-lg font-semibold">{ctx.name}</div>
            {ctx.tagline && <div className="text-sm opacity-80">{ctx.tagline}</div>}
          </div>
        </div>
      </header>
      <section className="px-6 py-14" style={{ background: ctx.brand.secondary }}>
        <div className="mx-auto max-w-5xl space-y-4">
          <h1 className="text-3xl font-semibold leading-tight md:text-4xl">
            {ctx.tagline || `Modern dentistry at ${ctx.name}.`}
          </h1>
          {ctx.address && <p className="opacity-80">{ctx.address}</p>}
          {ctx.phone && <p className="opacity-80">{ctx.phone}</p>}
        </div>
      </section>
      {featuredTreatments.length > 0 && (
        <section className="bg-white px-6 py-12">
          <div className="mx-auto max-w-5xl">
            <div
              className="mb-6 text-xs uppercase tracking-wide"
              style={{ color: ctx.brand.primary }}
            >
              Treatments
            </div>
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              {featuredTreatments.map((t) => (
                <div
                  key={t.name}
                  className="rounded-xl border p-4"
                  style={{ borderColor: `${ctx.brand.primary}22` }}
                >
                  <div className="text-base font-semibold">{t.name}</div>
                  {(t.priceFrom || t.priceTo) && (
                    <div className="text-sm" style={{ color: ctx.brand.primary }}>
                      {t.priceTo
                        ? `£${t.priceFrom}–£${t.priceTo}`
                        : t.priceFrom
                          ? `from £${t.priceFrom}`
                          : ""}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>
      )}
      <FloatingChat ctx={ctx} />
    </div>
  );
}
